language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: k0c4NB8sTm3rSxGDhivNZa0aWafAszsZX+o/47M9GjKQnZrw3JM1MRaz2R5hAMMc1AQbkCU7SwM3hBGHx09o2byenrrarFc7+mLnEpjnjc5FC/jcZE6C6+1m8t8bd2qSL0C+x7F6xRKmYnotu0TPhAEclU/nwvVgqPsKYfWhrzqkOkc6i8OAfhyKzskVgbFVbaC+CnQB9nel9XsYYLWevlGkoldtM1i81TKBaDEPyfwdmaR11ijIUCAemANkQJ7MNmWzFa5e8KiNFLnF+r7+9rNlIyvCzt9mil7UD94zGV56K3H3/g2D0lXz2EzO7Rznf8/UlcEo8+N9Tpw8HoEWgAbX1Rik/bf9UbmL8mvsVyVXO/owtd3uuRPejcHYTZhsi7GAJ+s45y3sTxbG6q4+Qcils4Vz/e7LDKf8BsvKJO/+7k82+Iy7daqjlEob04B0i/0L9NSV+j7H/poQnNWrNTOl1LoAGws4DjcviotSF/HxMFvuBuedVkQ2qtgbsjOCna+WAjTA1O4SbKuGoeRVE9W1CWZm7WRdHkPWjyOyIIzY/m74A6XlKemxYOb9lUTTWerzzdpGgyxjYeTJm8SVn4+GFBHQ742crmNvfgz6CgThnDNcUgmmYj2Wceg7sE5/V3f6oMkJr5SzKfge2OonXTr6jcM4kuCVVg1/3/LGguA=
  on:
    branch: master
    tags: true
