language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: n2h67bUKKrSieue4FM38WLQqr9dq1rwtO+h+MG0HDaY/7fRngRTu+r+W6kuIuKmAarWHop8arK/dwiyAzag2lY8m9wwk5PH994yzRF1lbUPpVicaJTLPPmequVbYMcNYDSqinh7plDeOXFN8LAH4uK0smx3ajwQZG2d5ZOPBGlwr2RQI1N6Bp4a+nzAWQFlq7bn5pv3jYJleuJZOCG4t6n1pB5kiERU9qxjlLIDyg4IQ7hkNEwERZIb1wIMtucSXR7FDMgqqOM9SIkMRmTRmGwX96NpAQSLBnL7KWGgEq1TstX566U5RiJNlOG9lfY2PJhJrS04q2qmzMqAiKsd9Y771PeQPd1R2uxNLZxR/0V/b8jnhqxxDJKxPhYdl79P1kcyMrXodhcKtXiKH4/W6eHVoIMLij9PXU80yhgeiRt7lQN9eWZ2roFblaaVjb7m2Zduo/z9qN5RzFC4O2Ao+SIkVEiXPlkvRf4shRlCDxwxUXST/l/8chpJLaKYucUKHNxh+zuxNPh+dZF8xMXAAXF6HJtu+9ItG2AXPxOQGWJhtPEEL+C6J5AlNcD7RTu1ZxDO46E95xwoqUo/DR0wEqGOey5jWpQtJNLDnp8pMIu1/NrMVpuNghQMKgZyVHUHMgrMsidTKcXWLTN1tJhOkP+QRg++UJnzD/kcUg4poJn8=
  on:
    branch: master
    tags: true
env:
  global:
    secure: tO9iH8Mh4+LxfoTCmpGv0UnMSaCAUODka4LzTMEGuDRP349sKwJZ8p6Hu25w5d88ru2iQUBTOWvjraQuBGZYRc6KTbfNK2fGXEAdMOKGCfyB/RaTMVI/QCLhF2Le6c5DWNZFO2NutmUhUCyOpkUagH1tfr4/LvFgTBk10f2j/OnX+VFOVIYFPU7EiyQbtK/vesWWHoj/4tAhct/Ujy64pJ2Up0vLWkXeNDewzK4yalEtSwq/A5R69Jijy+rXWxiaDLQicmW8rzAOgkOU+SDR/Mur40vSvzd3ThR36TfjZu0hlXLg+nBi3Ek0m4hiwSFLA7mxXWq3DyFfALYuNp45EjShk90xSID9mFmjs70wQgRg6N+ZwHmJJhcHsbflCMt0E24gk71g+ZjSoJKrjCd6AIsLYQPuJBpj/Ukq9b7eFGYnaVXgi3wQ+LG6NzY4rXh+mD6fI/lHGScLafGdCjuYRA+HXMNUAcRBmtjgWhhhSzkq9gBqWGlrbEKHIRR4LXpZghxjJbhEc/l4VgYyyurTZm8kdP+xK8TtQOWdTDFMEg0pBnyFEDj/QuznTwAx16nifbzoY9r1+C/Jz2T1N7dCc8wZLzgz98bknQLyRn+ey99NHdY3WMIM99MtScFYl0DhJClwV+eJ0fEZmHapDtgKu+/+IzWetqPy7pf7SE6qOaM=
