language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: ApCvPNDturThb7JzIWi6XdjrihCF2SChR/w8z5Nb8bg/Wcyf8a+2jBgYhlOj5a4SaP97JqjY3Jm/zXrNpfhpQlv+NJaeokiAbDthgqyFTfjSDINXgr0IL8fi90XkrjWKbSHtIDQ+uNnhfczn3P7ovxYLazN54z3hQDdpWfPfbQdvohcmHmmVsQFis/KjufhGgdawRM7HsJp6/63cjojuFi68AH/m0e8s5UZGP5Zfkwwx7ylzKocWaaZ5lBsjqeIBN42uUVDCKCT5EIx9z55OLFfN3Fvh9wCDWPzZO9Qq7Vc3qWxi3PRBs3jLyeCsKCnr1mRoIfSJoP7JKxrE5+UnRYKmLSeDKBkDVENbgTsmUvj8ThcnA4GC1b97ey3Z/oF9omjJd563I1INLLxlJ9dVZUoToE0n4SIZIZTbS5erw25wW+gSLMJcbl0AUfcDxzS16MW3zQTlKFHgFZdBUpynxcB5uyFc2u0eAN72tg6mE7T4R+omV9+wPNcebEGpAF2bSgHM9iGG+chzoZpo67HP4R7yCIKzsSfFUzdK4rRp1jq6vTSrh+XCWeMPL/68oAG+eO3KNsEafwOBMeN1vP75ra6zfyo2cDbXaSe2/BMf8ff8lOUvUfiewuZnuBnfhq4MnYKJv7dPq4ta7N5UbROSQPED/oQeSjSI8B9nozOTaFA=
  on:
    branch: master
    tags: true
env:
  global:
    secure: K3eb/EOABQ1dzp/4BJ51hXmuPgRRR2pZ15GWipNvEiTB/DinASHZg9pkVWOH37KxyITdRkwM2MQEM5ZRucS/mp4oOtMfFT+rGyYWH0ixZgCIme3kO86Bfx1EZWA9HjIkzFRgHcFIbIqZVow2ZLPo7UvrbG9KGA6SdEbgRzpWZm1164oS6Ci04N2X+awI1OhcokcLAuDw5lbjxLxXmnPIh3lcZawJKnIamo3BciiNEvf82hQaSEaENSHBfagxNDNK/HmPym9jMuTQ+FYYbIPi+THw0PGQlJ+89S1Q6vXj8s/EnKngnGJr9EzquSe4WmikRFGj4+Ki18TFuVhrOVRLuuA3xdJ3NTrTPbz25IADnL0bQXG88H9Zxf8wzW395sVhYm3LiW5KMI3Z5VAILl+Y9EAQoJlUEpSNiWSWNclL1ZcMIrt0NYIdrAgsZHMS0RjzzeG8zZE7QmP7vxTtOoFdvr7ANGfQxPhx28Jhg8fQ+tP++y7qj3OsRcF5LrxH47Mm0Z8ZzeG0kimsSxc0vk5eICAeqr3JIbziKNTCx39fQ92ZRLJBRmPa2gZrVRIQPwbWsXlUyv1v1dNpRujhVA+TTe9lBV1Q7vKfVdZCRKIdc7eWplhQSluiLV3bECsy/YBNY39Dxt6fC6GloXF+56Sg3dcONTLZe1djKuohn+2jZz8=
