language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: ApCvPNDturThb7JzIWi6XdjrihCF2SChR/w8z5Nb8bg/Wcyf8a+2jBgYhlOj5a4SaP97JqjY3Jm/zXrNpfhpQlv+NJaeokiAbDthgqyFTfjSDINXgr0IL8fi90XkrjWKbSHtIDQ+uNnhfczn3P7ovxYLazN54z3hQDdpWfPfbQdvohcmHmmVsQFis/KjufhGgdawRM7HsJp6/63cjojuFi68AH/m0e8s5UZGP5Zfkwwx7ylzKocWaaZ5lBsjqeIBN42uUVDCKCT5EIx9z55OLFfN3Fvh9wCDWPzZO9Qq7Vc3qWxi3PRBs3jLyeCsKCnr1mRoIfSJoP7JKxrE5+UnRYKmLSeDKBkDVENbgTsmUvj8ThcnA4GC1b97ey3Z/oF9omjJd563I1INLLxlJ9dVZUoToE0n4SIZIZTbS5erw25wW+gSLMJcbl0AUfcDxzS16MW3zQTlKFHgFZdBUpynxcB5uyFc2u0eAN72tg6mE7T4R+omV9+wPNcebEGpAF2bSgHM9iGG+chzoZpo67HP4R7yCIKzsSfFUzdK4rRp1jq6vTSrh+XCWeMPL/68oAG+eO3KNsEafwOBMeN1vP75ra6zfyo2cDbXaSe2/BMf8ff8lOUvUfiewuZnuBnfhq4MnYKJv7dPq4ta7N5UbROSQPED/oQeSjSI8B9nozOTaFA=
  on:
    branch: master
    tags: true
